### PR TITLE
Created Java folder with resources and dsa

### PR DESCRIPTION
**Pull request by tamal-kundu**

### CODE REVIEW

**Comment by tamal-kundu** [comment]
Will be adding more resources and dsa q/a..
please tag my pr with hacktoberfest and hactoberfest accepted

**Comment by tamal-kundu** [comment]
Will be adding more resources and dsa q/a..
please tag my pr with hacktoberfest and hactoberfest accepted

**Comment by charan-143** [comment]
can I add some DSA algorithms of insertion, deletion.,stack etc

**Comment by AlphaLaser** [comment]
Sorry man, DSA questions and solutions won't work. This repo is only for coding notes and relevant resources.

Also, in the hello world file, please add more stuff like the background of Java, Variables, Data types etc.

**Pull request closed without merging**
